# Generated by Django 4.2.4 on 2024-02-25 11:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('img', models.ImageField(blank=True, upload_to='event/img/%Y')),
                ('show', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('adddate', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
            ],
        ),
    ]
