# Generated by Django 4.2.4 on 2024-02-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
